### ISSUE TITLE
TypeError: notify.error is not a function

### ISSUE THREAD

**Issue by cornips** [raelbr/console-log-checker#1]
When running console-log-checker without any console.logs in files, it will pass.
```zsh
$ npx console-log-checker

✓  No console.log found

```

But when running console-log-checker _with_ a console.log() in a file:

```zsh
$ npx console-log-checker
./node_modules/console-log-checker/lib/services/file.js:61
    notify.error("error", "An error has occurred!");
           ^

TypeError: notify.error is not a function
    at getFilesWithLog (./node_modules/console-log-checker/lib/services/file.js:61:12)
    at async init (./node_modules/console-log-checker/lib/index.js:17:24)

```

Tested with Node 16, 18, and 19. All with the same result.

**Comment by raelbr** [comment]
Hey, sorry about the late reply. I will merge your PR! =)
Thanks for your collaboration!
